### ISSUE TITLE
Combine Team and About Us

### ISSUE THREAD

**Issue by Aniq55** [ieeesb-nitdgp/Research-Web-Portal#15]
Combine Team and About us, into a single tab called "Team" and remove it from the landing page.
Make it a separate page. Keep the landing page as minimal as possible.

> It will be nice to add a story about how we came up with this idea and got it approved in a short time.

**Comment by pritish083** [comment]
I will start working on it from today.

**Comment by pritish083** [comment]
I am taking up this issue !

**Comment by monsij** [comment]
Updates @pritish083  ? Been a long time
