### ISSUE TITLE
Reposition logo image

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/Research-Web-Portal#17]
![Capture](https://user-images.githubusercontent.com/23289387/59219931-49d81d00-8bcc-11e9-88a8-7a7430afb1ca.JPG)

Position accordingly

**Comment by monsij** [comment]
The issue persists even on `login_f.html`
![Capture2](https://user-images.githubusercontent.com/23289387/59255492-7aeb3880-8c32-11e9-8e9a-f3d6448bb2bf.JPG)

**Comment by pritish083** [comment]
Okay.

**Comment by monsij** [comment]
@MohitKochar

**Comment by MohitKochar** [comment]
ok will try to complete it by tomorrow @monsij
