### ISSUE TITLE
Improper redirect

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/Research-Web-Portal#29]
On clicking, the thumbnail of research portal does not redirects to the home page. Make corresponding changes on all related locations.

**Screenshot**
![home_redirect](https://user-images.githubusercontent.com/23289387/70514744-2af61b80-1b5a-11ea-80dd-b0c8c85b91f6.JPG)

**Comment by sagar-wal** [comment]
I'll be able to solve this issue.

**Comment by monsij** [comment]
Go for it!. Do remember to open a PR from a new branch (other than master) with all commits squashed into a single one.

**Comment by prabalsingh24** [comment]
Is it still open? @sagar-wal you doing it right?

**Comment by sagar-wal** [comment]
> Is it still open? @sagar-wal you doing it right?

Yes. I'm on it.

**Comment by sagar-wal** [comment]
@monsij On clicking the thumbnail of IEEE SB NITD, should it also redirect to homepage ?
![image](https://user-images.githubusercontent.com/53569839/70695350-843f8580-1ce7-11ea-822b-18573cf26d98.png)

**Comment by monsij** [comment]
Yes. For now do it

**Comment by sagar-wal** [comment]
I have resolved this issue and opened a pull request for the same.
