### ISSUE TITLE
Maintain aspect ratio of logos

### ISSUE THREAD

**Issue by Aniq55** [ieeesb-nitdgp/Research-Web-Portal#6]
I see the aspect ratios of the logos are violated in many places.
Please stick to the original.

**Comment by ZER-0-NE** [comment]
Many places? I just put one logo for now. <('.')>

**Comment by Aniq55** [comment]
What is the link? I saw three logos, all with wrong AR

**Comment by Aniq55** [comment]
Wrong aspect ratio, destroys the whole look of the design. Please make it a high priority task.
